//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.CourseClass = new HashSet<CourseClass>();
            this.User = new HashSet<User>();
            this.UserFile = new HashSet<UserFile>();
            this.Course = new HashSet<Course>();
        }
    
        public int ClassID { get; set; }
        public int DepartmentID { get; set; }
        public string ClassName { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<CourseClass> CourseClass { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<UserFile> UserFile { get; set; }
        public virtual ICollection<Course> Course { get; set; }
    }
}
