//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TeacherCourse = new HashSet<TeacherCourse>();
            this.UserFile = new HashSet<UserFile>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public int UserType { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string UserEmail { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<TeacherCourse> TeacherCourse { get; set; }
        public virtual ICollection<UserFile> UserFile { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
