//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFile
    {
        public int UserFileID { get; set; }
        public string FName { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
        public string FileType { get; set; }
        public System.DateTime UploadTime { get; set; }
        public string UploaderID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
